import { Footer, Navigation, NextAuthProvider } from "@/components";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "E-Commerce from scratch with Coding with Dawid || Yoga723",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>E-Commerce from scratch with Coding with Dawid || Yoga723</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </head>
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
